apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This example uses the Kustomize resources directly from the verify service's own kustomize directory.
# You can add patches or other customizations here if needed.
resources:
  - ../../../verify/kustomize
