apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pomerium-demo-apps

resources:
  - namespace.yaml
  - hello-world.yaml
  - admin-panel.yaml
  - grafana.yaml
  - ingresses.yaml

configMapGenerator:
  - name: demo-config
    literals:
      - domain=demo.pomerium.com
      - environment=demo
      - purpose=pomerium-public-demo

commonLabels:
  app.kubernetes.io/part-of: pomerium-demo
  app.kubernetes.io/managed-by: kustomize

images:
  - name: gcr.io/google-samples/hello-app
    newTag: "2.0"
  - name: grafana/grafana
    newTag: "latest"
  - name: nginx
    newTag: "alpine"