apiVersion: v1
kind: Service
metadata:
  name: {{ include "pomerium-zero.fullname" . }}
  labels:
    {{- include "pomerium-zero.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "pomerium-zero.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      targetPort: https
      protocol: TCP
      name: https
  externalTrafficPolicy: Local
