#!/bin/bash
set -euo pipefail

CORE_VERSION="${CORE_VERSION?'CORE_VERSION is required'}"
ENTERPRISE_VERSION="${ENTERPRISE_VERSION?'ENTERPRISE_VERSION is required'}"
INGRESS_CONTROLLER_VERSION="${INGRESS_CONTROLLER_VERSION?'INGRESS_CONTROLLER_VERSION is required'}"

download-file() {
  local _dst="${1}"
  local _url="${2}"
  echo "updating $_dst from $_url"
	curl -s -o "$_dst" -z "$_dst" "$_url"
}

sed-file() {
  local _dst="${1}"
  local _pattern="${2}"
  local _tmp
  echo "updating $_dst using $_pattern"
  _tmp="$(mktemp /tmp/config.XXXXXXXXXX)"
  sed -E "$_pattern" "$_dst" > "$_tmp"
  mv "$_tmp" "$_dst"
}

download-file "./ingress-controller/kustomize/crd/bases/ingress.pomerium.io_pomerium.yaml" \
  "https://raw.githubusercontent.com/pomerium/ingress-controller/refs/tags/v$INGRESS_CONTROLLER_VERSION/config/crd/bases/ingress.pomerium.io_pomerium.yaml"

sed-file ./ingress-controller/terraform/variables.tf \
  '/image_tag/{n;n;n;s/".*"/"v'"$INGRESS_CONTROLLER_VERSION"'"/}'

sed-file ./recipe/ingress-controller-enterprise-terraform-gke/README.md \
  's/(ref=)(v.*)/\1v'"$INGRESS_CONTROLLER_VERSION"'/g'

sed-file ./enterprise/terraform/kubernetes/variables.tf \
  '/image_tag/{n;n;n;s/".*"/"v'"$ENTERPRISE_VERSION"'"/}'

sed-file ./zero/helm/Chart.yaml \
  's/(version: )(.*)/\1'"$CORE_VERSION"'/g'

sed-file ./zero/helm/Chart.yaml \
  's/(appVersion: )(.*)/\1v'"$CORE_VERSION"'/g'
