name: Publish Helm Chart (dev)
on:
  push:
    branches:
      - main
    paths:
      - "zero/helm/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install Helm CLI
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
      - name: Set dev version
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          VERSION="0.0.0-git.${SHORT_SHA}"
          sed -i "s/^version:.*/version: ${VERSION}/" ./zero/helm/Chart.yaml
          echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
      - name: Login
        run: |
          helm registry login registry-1.docker.io --username="${{ secrets.DOCKERHUB_USER }}" --password="${{ secrets.DOCKERHUB_SECRET_1124 }}"
      - name: Package Chart
        run: |
          helm package ./zero/helm
      - name: Push Chart
        run: |
          find . -maxdepth 1 -type f -name "pomerium-zero-*.tgz" -exec helm push {} oci://registry-1.docker.io/pomerium \;
